### ISSUE TITLE
Prevent grass->dirt paths as well?

### ISSUE THREAD

**Issue by gbl** [PotatoPresident/NoStrip#1]
Great mod, I really like how I won't strip logs accidentially any more. For example when clicking a button that's attached to a log.

However, turning grass into dirt roads can be just as annoying, what about preventing that as well? It's the same kind of "right click shouldn't do stuff" after all.

**Comment by PotatoPresident** [comment]
I add this to my todo list

**Comment by PotatoPresident** [comment]
Sorry I never really got around to this myself. Have been busy and also mostly forgot. Thanks for doing it for me! Update is out now on [curseforge](https://www.curseforge.com/minecraft/mc-mods/no-strip/files/3119982)
