### ISSUE TITLE
Game Crashes when attempting to make a Dirt Path with a shovel [1.19]

### ISSUE THREAD

**Issue by NicoTheCinderace** [PotatoPresident/NoStrip#18]
[crash-2022-06-18_10.26.41-client.txt](https://github.com/PotatoPresident/NoStrip/files/8934590/crash-2022-06-18_10.26.41-client.txt)

Attached is a crashlog that happens every time I attempt to use a shovel on a dirt path with this mod.

**Comment by PotatoPresident** [comment]
Updated
